"""Declarative base and shared column conventions.

Everything every table needs lives here, so individual model files stay short
and consistent.

Two conventions worth understanding:

1. **Constraint naming.** By default, databases invent names for indexes and
   constraints. Those invented names differ between PostgreSQL and SQLite, and
   Alembic then cannot generate a migration that says "drop the constraint
   called X" -- because it doesn't know what X is called. The
   `naming_convention` below forces every constraint to get a predictable name
   like `uq_transactions_account_id_plaid_transaction_id`. Setting this on day
   one avoids a genuinely painful class of migration failure later.

2. **UUID primary keys instead of auto-incrementing integers.** Integer IDs
   leak information (a user seeing `/transactions/4` knows you have very few
   transactions) and they collide when merging data from multiple sources.
   UUIDs are generated by the application, so we know a record's ID *before*
   we insert it -- which makes batch-inserting a Plaid sync much simpler.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Adds a UUID `id` primary key generated by Python, not the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds `created_at` / `updated_at`, maintained by the database itself.

    `server_default=func.now()` means PostgreSQL fills these in. That is
    deliberate: if a row is ever inserted by a script, a migration, or a
    database admin rather than by our app, the timestamps are still correct.
    Never trust the application clock to be the only source of truth.

    All timestamps are timezone-aware (`TIMESTAMPTZ`). Storing naive local
    times is one of the most common and most painful data-integrity bugs --
    daylight-saving transitions silently corrupt ordering.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
