"""add users last_seen_at

Revision ID: 7c3fd28a1580
Revises: fc0c7beca47e
Create Date: 2026-07-28 10:24:45.250083

Your first incremental migration -- a change to a schema that already exists,
rather than creating one from nothing.

Is this safe to run on a live production database? Yes, and it is worth
knowing exactly why, because the answer is not always yes:

  * Adding a NULLABLE column with no default is a metadata-only change in
    PostgreSQL. It does not rewrite the table and it takes a lock for
    microseconds, so it is safe even with millions of rows.
  * Adding a NOT NULL column WITHOUT a default would be rejected outright --
    existing rows would have nothing to put in it.
  * Adding a NOT NULL column WITH a default is fine on PostgreSQL 11+, which
    stores the default in the catalog instead of rewriting every row. On
    older versions this rewrites the whole table and locks it for the
    duration -- an outage on a large table.

The habit to build: before running any migration against real data, ask
"does this rewrite the table, and how long does it hold a lock?"
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3fd28a1580'
down_revision: Union[str, None] = 'fc0c7beca47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
