"""initial schema

Revision ID: 13005205e074
Revises: 
Create Date: 2026-07-28 02:25:40.573857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13005205e074'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('plaid_institution_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('website_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_index(op.f('ix_institutions_plaid_institution_id'), 'institutions', ['plaid_institution_id'], unique=True)
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'restore', name='ck_auditaction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor', sa.Enum('user', 'sync', 'rule', 'system', name='ck_auditactor', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_entity_type_entity_id', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_user_id_created_at', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'parent_id', 'name', name='uq_categories_user_id_parent_id_name', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('plaid_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('plaid_item_id', sa.String(length=128), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('transactions_cursor', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('healthy', 'login_required', 'error', 'disconnected', name='ck_plaiditemstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_plaid_items_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plaid_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_items'))
    )
    op.create_index(op.f('ix_plaid_items_institution_id'), 'plaid_items', ['institution_id'], unique=False)
    op.create_index(op.f('ix_plaid_items_plaid_item_id'), 'plaid_items', ['plaid_item_id'], unique=True)
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_table('rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stop_processing', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index('ix_rules_user_id_priority', 'rules', ['user_id', 'priority'], unique=False)
    op.create_table('tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_id_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.UUID(), nullable=True),
    sa.Column('plaid_account_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('user_display_name', sa.String(length=255), nullable=True),
    sa.Column('mask', sa.String(length=8), nullable=True),
    sa.Column('type', sa.Enum('depository', 'credit', 'loan', 'investment', 'other', name='ck_accounttype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('include_in_net_worth', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_accounts_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('plaid_account_id', name='uq_accounts_plaid_account_id')
    )
    op.create_index(op.f('ix_accounts_plaid_item_id'), 'accounts', ['plaid_item_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_index('ix_accounts_user_id_is_active', 'accounts', ['user_id', 'is_active'], unique=False)
    op.create_table('merchants',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], name=op.f('fk_merchants_default_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_merchants_user_id_normalized_name', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_merchants_default_category_id'), 'merchants', ['default_category_id'], unique=False)
    op.create_index('ix_merchants_normalized_name', 'merchants', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_merchants_user_id'), 'merchants', ['user_id'], unique=False)
    op.create_table('sync_history',
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Enum('webhook', 'scheduled', 'manual', 'initial', name='ck_synctrigger', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', 'partial', name='ck_syncstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_before', sa.Text(), nullable=True),
    sa.Column('cursor_after', sa.Text(), nullable=True),
    sa.Column('transactions_added', sa.Integer(), nullable=False),
    sa.Column('transactions_modified', sa.Integer(), nullable=False),
    sa.Column('transactions_removed', sa.Integer(), nullable=False),
    sa.Column('transactions_skipped', sa.Integer(), nullable=False),
    sa.Column('accounts_updated', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_sync_history_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_history'))
    )
    op.create_index('ix_sync_history_plaid_item_id_started_at', 'sync_history', ['plaid_item_id', 'started_at'], unique=False)
    op.create_table('account_balances',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_balances_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_balances')),
    sa.UniqueConstraint('account_id', 'as_of', name='uq_account_balances_account_id_as_of')
    )
    op.create_index('ix_account_balances_account_id_as_of', 'account_balances', ['account_id', 'as_of'], unique=False)
    op.create_table('merchant_aliases',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('raw_pattern', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_aliases_merchant_id_merchants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_aliases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_aliases')),
    sa.UniqueConstraint('user_id', 'raw_pattern', name='uq_merchant_aliases_user_id_raw_pattern', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_merchant_aliases_merchant_id'), 'merchant_aliases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_aliases_user_id'), 'merchant_aliases', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('plaid', 'manual', 'csv_import', name='ck_transactionsource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'posted', 'removed', name='ck_transactionstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaces_plaid_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('raw_merchant_name', sa.Text(), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('raw_currency_code', sa.String(length=3), nullable=False),
    sa.Column('raw_date', sa.Date(), nullable=False),
    sa.Column('raw_authorized_date', sa.Date(), nullable=True),
    sa.Column('raw_category', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_merchant_id', sa.UUID(), nullable=True),
    sa.Column('auto_category_id', sa.UUID(), nullable=True),
    sa.Column('auto_category_source', sa.Enum('none', 'plaid', 'rule', 'heuristic', 'model', name='ck_categorysource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('auto_rule_id', sa.UUID(), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('user_merchant_id', sa.UUID(), nullable=True),
    sa.Column('user_category_id', sa.UUID(), nullable=True),
    sa.Column('user_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('user_date', sa.Date(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auto_category_id'], ['categories.id'], name=op.f('fk_transactions_auto_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['auto_merchant_id'], ['merchants.id'], name=op.f('fk_transactions_auto_merchant_id_merchants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['auto_rule_id'], ['rules.id'], name=op.f('fk_transactions_auto_rule_id_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_category_id'], ['categories.id'], name=op.f('fk_transactions_user_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_merchant_id'], ['merchants.id'], name=op.f('fk_transactions_user_merchant_id_merchants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('account_id', 'fingerprint', name='uq_transactions_account_id_fingerprint'),
    sa.UniqueConstraint('account_id', 'plaid_transaction_id', name='uq_transactions_account_id_plaid_transaction_id')
    )
    op.create_index('ix_transactions_account_id_raw_date', 'transactions', ['account_id', 'raw_date'], unique=False)
    op.create_index(op.f('ix_transactions_replaces_plaid_transaction_id'), 'transactions', ['replaces_plaid_transaction_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_user_id_auto_category_id', 'transactions', ['user_id', 'auto_category_id'], unique=False)
    op.create_index('ix_transactions_user_id_auto_merchant_id', 'transactions', ['user_id', 'auto_merchant_id'], unique=False)
    op.create_index('ix_transactions_user_id_raw_date', 'transactions', ['user_id', 'raw_date'], unique=False)
    op.create_index('ix_transactions_user_id_user_category_id', 'transactions', ['user_id', 'user_category_id'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_transaction_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_tags_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id', name=op.f('pk_transaction_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tags')
    op.drop_index('ix_transactions_user_id_user_category_id', table_name='transactions')
    op.drop_index('ix_transactions_user_id_raw_date', table_name='transactions')
    op.drop_index('ix_transactions_user_id_auto_merchant_id', table_name='transactions')
    op.drop_index('ix_transactions_user_id_auto_category_id', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_replaces_plaid_transaction_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_id_raw_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_merchant_aliases_user_id'), table_name='merchant_aliases')
    op.drop_index(op.f('ix_merchant_aliases_merchant_id'), table_name='merchant_aliases')
    op.drop_table('merchant_aliases')
    op.drop_index('ix_account_balances_account_id_as_of', table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index('ix_sync_history_plaid_item_id_started_at', table_name='sync_history')
    op.drop_table('sync_history')
    op.drop_index(op.f('ix_merchants_user_id'), table_name='merchants')
    op.drop_index('ix_merchants_normalized_name', table_name='merchants')
    op.drop_index(op.f('ix_merchants_default_category_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index('ix_accounts_user_id_is_active', table_name='accounts')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_plaid_item_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_rules_user_id_priority', table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_plaid_item_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_institution_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_audit_log_user_id_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_entity_type_entity_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_institutions_plaid_institution_id'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
